### ISSUE TITLE
Curious about hasingFn

### ISSUE THREAD

**Issue by purpurplr** [egorgrushin/painless-redux#17]
https://github.com/egorgrushin/painless-redux/blob/41f506e233638f21581a3aa9d85c2f532248f2eb/src/utils.ts#L13

Hi 🙃
I was wondering, why hashing strings?
I was trying to get dictionary of pages, and it seems there is no way to do it without going through pain.

Painless redux API has no method for retrieving a dictionary of pages, but even when selected by the usual selectors, pages dictionary is meaningless, because the keys are hashed.

There is an `hashFn` option in the entity config, but it seems it only applies to selectors - and action creators are using the default hashing function no matter what. If it wasn't the case, I could use a custom hashing functions that would not hash primitive values - and i would get a meaningful pages dictionary.

Is this behaviour intentional?
Sorry for annoyance ❤️

**Comment by egorgrushin** [comment]
Hi @purpurplr

> Painless redux API has no method for retrieving a dictionary of pages

I guess a `getDictionary$`is what you need.

> Is this behaviour intentional?

It is a good question! I guess pages' keys were not intended for public use, so I just wanted to deal with hashed strings instead of either hash or meaningful string. However, I guess I could save this behavior, but make a config.hashFn to be invoked everywhere it should be invoked. There is PR for this feature: #28 
This will be released in 4.1.17 - https://www.npmjs.com/package/painless-redux/v/4.1.17
